<?php

function markup($namespace_list) {
  if($namespace_list){
    $markup = '<div class="homepageSection">
    <div class="homepageText">';
    foreach ($namespace_list as $namespace) {
      $prefix = $namespace;
      $prefix_class = $prefix . 'Link';
      $record = get_record($namespace);
      $logo = file_or_default($record,'logo','/sites/all/themes/ldl/images/NpfYQT0.png');
      $fp_logo = file_or_default($record,'fp_logo','/sites/all/themes/ldl/images/NpfYQT0.png');
      $markup .= "<div><a  class='institutionLink $prefix_class' href='/$prefix'>";
      $title = get_field_or_default('title', $record, $namespace);
      // $image = get_field_or_default('logo', $record, $namespace);
      $color = isset($record->color) && strlen($record->color) > 0? $record->color : '#ffffff';
      $markup .= "<img src='$fp_logo' style='background-color:$color'><div class='institutionLink_meta'>$title</div></img></a></div>";
    }
    $markup .= "</div></div>";
    return array('#markup' => $markup);
  }
  else{
    return '';
  }
}



function file_or_default($record, $key, $default){
  $logo = isset($record->$key) ? $record->$key : $default ;
  if (isset($record->$key)) {
    $file = file_load($record->$key);
    $logo = file_create_url($file->uri);
  }
  return $logo;
}

function generate_markup() {
  if (module_exists('islandora_namespace_homepage')) {
    $list = get_namespace_prefixes(FALSE);
    $markup = markup($list);
  }
  return $markup;
}

function islandora_custom_homepage_blocks_block_info() {
  $blocks = array();
  $blocks['homepage_institution_list'] = array(
    'info' => t('Homepage Custom Block Institution List'),
    'status' => TRUE,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '<front>',
  );
  return $blocks;
}

function islandora_custom_homepage_blocks_block_view($delta = '') {
  switch ($delta) {
    case ('homepage_institution_list') :
       $block['content'] = generate_markup();
       $block['visibility'] = BLOCK_VISIBILITY_LISTED;
       $block['pages'] = '<front>';
       $block['region'] = 'content';
       $block['title'] = '<none>';
    break;
  }
  return $block;
}
